spring.application.name=api-gateway

server.port=8080

spring.main.web-application-type=reactive

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#id is just a unique name for this route.
spring.cloud.gateway.server.webflux.routes[0].id=employee-service-route

#lb = Load Balancer , employee-service = service name registered in Eureka
spring.cloud.gateway.server.webflux.routes[0].uri=lb://employee-service

#predicate means condition to match request/path
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/employees/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=DEBUG

spring.cloud.gateway.server.webflux.routes[1].id=department-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://department-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/department/**




